server:
  address: ":8080"
  mode: "debug"

dingtalk:
  appKey: "ding2qr7cxolnro023zk"
  appSecret: "75ymUMSM3mOVufYGCim3GjFI8Fys8huXX5QkZR4eLnL_RggXHpk1u5WTrPZKBBez"
  agentId: "your-agent-id"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  dbname: "dingtalk_service"
redis:
  addr: "localhost:6379"
  password: ""
  db: 0 